version: '3'
services:
  reddit_comment_api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        project: ./reddit_comment_api
    restart: on-failure
    ports: 
      - "8080:8080"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB_NAME=postgres